//created on: Apr 13, 2019
//list any import classes here.

package com.baske
import com.baske.model.*
import java.util.Set
import java.util.List
import java.time.LocalDate

//declare any global variables here
global Bolest prehlada;
global Bolest groznica;
global Bolest upalaKrajnika;
global Bolest sinusnaInfekcija;


rule "da li postoji pregled"
agenda-group "prva"
	when
		$set: Set() from collect(Pregled())
	then
	
	 System.out.println("postoji  " + $set.size() + " pregled/a");
end


rule "prehlada moze biti"
agenda-group "prva"
salience 300
	when
		$p : Pregled( $sim :  simptomi, $mogucaB : moguceBolesti  )  and
		$sss : Set() from collect($s : Simptomi(
//			this== Simptomi.CURENJE_IZ_NOSA ||
//			this== Simptomi.BOL_U_GRLU ||
//			this== Simptomi.GLAVOBOLJA ||
//			this== Simptomi.KIJANJE ||
//			this== Simptomi.KASALJ
			this memberOf  prehlada.getSimptomi()
			
		 ) from $sim) and
		eval($sss.size() >=4) 
		 
		$dajMiBolest : MogucaBolest(  naziv =="prehlada") from $mogucaB
		
	then
		System.out.println("moze biti glavobolja    poklapa se: "  + $sss.size()+"/"+prehlada.getSimptomi().size()+ "  poklapanja "  +$sss.size()/prehlada.getSimptomi().size());

		//$dajMiBolest.setMogucnost($sss.size()/5.0);
		//$dajMiBolest.setMogucnost($sss.size()/prehlada.getSimptomi().size());
		$dajMiBolest.setMogucnost($sss.size()/5.0);
		System.out.println($sss.size()+"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
		System.out.println($p.getMoguceBolesti().toString()+"\n");

end


rule "groznica moze biti"
agenda-group "prva"

salience 300
	when
		$p : Pregled( $sim :  simptomi ,  $mogucaB : moguceBolesti) and
		$sss : Set() from collect($s : Simptomi(
			this== Simptomi.KIJANJE ||
			this== Simptomi.BOL_U_GRLU ||
			this== Simptomi.KASALJ ||
			this== Simptomi.TEMPERATURA_VECA_OD_38 ||
			this== Simptomi.CURENJE_IZ_NOSA ||
			this== Simptomi.GLAVOBOLJA ||
			this== Simptomi.DRHTAVICA
			
		 ) from $sim) and
		eval($sss.size() >=4) 
		$dajMiBolest : MogucaBolest(  naziv =="groznica") from $mogucaB
		
	then
	System.out.println("moze biti groznica    poklapa se: "  + $sss.size() +"/7 poklapanja "  +$sss.size()/7.0);

	$dajMiBolest.setMogucnost($sss.size()/7.0);
	System.out.println($p.getMoguceBolesti().toString()+"\n");
	//$p.getMoguceBolesti().
	

end

rule "upalaKrajnika moze biti"
agenda-group "prva"
salience 300

	when
		$p : Pregled( $sim :  simptomi,   $mogucaB : moguceBolesti) and
		$sss : Set() from collect($s : Simptomi(
			this== Simptomi.BOL_U_GRLU ||
			this== Simptomi.BOL_KOJI_SE_SIRI_OD_USIJU ||
			this== Simptomi.GLAVOBOLJA ||
			this== Simptomi.TEMPERATURA_OD_40_DO_41 ||
			this== Simptomi.DRHTAVICA ||
			this== Simptomi.GUBITAK_APETITA ||
			this== Simptomi.UMOR ||
			this== Simptomi.ZUTI_SEKRET_IZ_NOSA
			
		 ) from $sim) and
		eval($sss.size() >=4) 
		  $dajMiBolest : MogucaBolest(  naziv =="upalaKrajnika") from $mogucaB
		
	then
	
		System.out.println("moze biti upalaKrajnika    poklapa se: "  + $sss.size() +"/8 poklapanja "  +$sss.size()/8.0);
		$dajMiBolest.setMogucnost($sss.size()/8.0);
	System.out.println($p.getMoguceBolesti().toString()+"\n");

end

rule "bolovanje od prehlada ili groznice u poslednjih 60 dana"
agenda-group "prva"
salience 330

	when
		$p : Pregled($pac :pacient )
		$pacient : Pacient( this == $pac, $ter:terapije  ) from $pac
		$l: List (size >0 ) from collect ($ppppp:PrepisanaTerapija( 
			(bolest.nazivBolesti =="groznica" || bolest.nazivBolesti =="prehlada" ) 
			&& $ppppp.terapijaPrepisanaDoSestMeseciPre()
		 	)from $ter) 

 	then
 		System.out.println("\npacijent je bolovao od prehlade ili groznice u poslednjih 6 meseci xxxxxxxxxxxxxxxYYYYYXXXXxxxxxxxxxxxxxxxx");
		System.out.println("xXXXXXXXXXXXXXXXXXXXXYYYYXXXXxxxxxxxAAAAAAAAAAAxxxxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
		System.out.println($l);
		System.out.println("xxxxxxxxxxxxxxxXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxxxxx\n");
		//dodaj da jeste pre 6 meseci bilo
		$p.getSimptomi().add(Simptomi.BOLOVANJE_OD_PREHLADE_ILI_GROZNICE_U_POSEDNJIH_60_DANA);

		
end

rule "temperatura veca od 38"
agenda-group "prva"
salience 330
	when
		$p : Pregled( $temp:temeratura  )
		eval($temp>38.0)
		
	then
		$p.getSimptomi().add(Simptomi.TEMPERATURA_VECA_OD_38);
end

rule "temperatura veca od 38 za terecu grupu jer treba"
agenda-group "treca"
salience 330
	when
		$p : Pregled( $temp:temeratura  )
		eval($temp>38.0)
		
	then
		$p.getSimptomi().add(Simptomi.TEMPERATURA_VECA_OD_38);
		System.out.println("TEMEPERATURA JE VECA OD 38 TRECA GRUPA\n");
		
end

rule "temperatura izmedju 40 i 41"
agenda-group "prva"
salience 330
	when
		$p : Pregled( $temp:temeratura  )
		eval($temp>40.0)
		eval($temp<41.0)
		
	then
		$p.getSimptomi().add(Simptomi.TEMPERATURA_OD_40_DO_41);
end


rule "sinusnaInfekcija moze biti"
agenda-group "prva"
salience 300

	when
		$p : Pregled( $sim :  simptomi, $mogucaB : moguceBolesti   )  and
		$sss : Set() from collect($s : Simptomi(
			this== Simptomi.OTICANJE_OKO_OCIJU ||
			this== Simptomi.GLAVOBOLJA ||
			this== Simptomi.ZUTI_SEKRET_IZ_NOSA ||
			this== Simptomi.BOL_U_GRLU ||
			this== Simptomi.TEMPERATURA_VECA_OD_38 ||
			this== Simptomi.KASALJ ||
			this== Simptomi.BOLOVANJE_OD_PREHLADE_ILI_GROZNICE_U_POSEDNJIH_60_DANA
			
			
		 ) from $sim) and
		eval($sss.size() >=4) 
		$dajMiBolest : MogucaBolest(  naziv =="sinusnaInfekcija") from $mogucaB
	then
		System.out.println("moze biti sinusnaInfekcija    poklapa se: "  + $sss.size() +"/7 poklapanja "  +$sss.size()/7.0);
	

	$dajMiBolest.setMogucnost($sss.size()/7.0);
	System.out.println($p.getMoguceBolesti().toString()+"\n");
	
end



rule "nadji najbolu mogucnost"
agenda-group "prva"
salience 200
	when
		$p :Pregled( $mog : moguceBolesti    )
		//$m : MogucaBolest(  ) from $mog
		$n: Double(doubleValue>=0.0) from accumulate(
			$m:MogucaBolest( $mm:mogucnost ) 
			from $mog,
			max($mm)
		)
	then
		$p.setNajboljaProcenaBolesti($n);
		System.out.println("najboljaProcena postavljena u pregled " + $p.getNajboljaProcenaBolesti()+"\n");

end

//

rule "da li je prehlada"
agenda-group "prva"
salience 105
enabled false
	when
		$p: Pregled( $mog: moguceBolesti , $pro : najboljaProcenaBolesti  )
		$s : List(size >0) from collect( $m : MogucaBolest( mogucnost == $pro && naziv == prehlada.getNazivBolesti()) from $mog
		)
	then

		PrepisanaTerapija t = new PrepisanaTerapija(prehlada,null,null,null);
		$p.getPacient().getTerapije().add(t);
		
			int temp = $p.getPacient().getTerapije().size();
			System.out.println("\nbolest koja je izabrana je prehlada: \n"+$p.getPacient().getTerapije().
			get(temp-1).getBolest().toString()+"\n");
end

rule "da li je groznica"
agenda-group "prva"
salience 107
enabled false
	when
		$p: Pregled( $mog: moguceBolesti , $pro : najboljaProcenaBolesti  ) and
		$s : List(size >0 ) from collect( $m : MogucaBolest( mogucnost == $pro && naziv == groznica.getNazivBolesti()) from $mog

		)
	then

		PrepisanaTerapija t = new PrepisanaTerapija(groznica,null,null,null);
		$p.getPacient().getTerapije().add(t);
		
			int temp = $p.getPacient().getTerapije().size();
			System.out.println("\nbolest koja je izabrana je groznica: \n"+$p.getPacient().getTerapije().
			get(temp-1).getBolest().toString()+"\n");
end

rule "da li je upalaKrajnika"
agenda-group "prva"
salience 108
enabled false
	when
		$p: Pregled( $mog: moguceBolesti , $pro : najboljaProcenaBolesti  )
		$s : List(size >0) from collect( $m : MogucaBolest( mogucnost == $pro && naziv == upalaKrajnika.getNazivBolesti()) from $mog
		)
	then

		PrepisanaTerapija t = new PrepisanaTerapija(upalaKrajnika,null,null,LocalDate.now());
		$p.getPacient().getTerapije().add(t);
		
			int temp = $p.getPacient().getTerapije().size();
			System.out.println("\nBolest koja je izabrana je upalaKrajnika: \n"+$p.getPacient().getTerapije().
			get(temp-1).getBolest().toString() +" vreme "
			+ $p.getPacient().getTerapije().get(temp-1).getDatumPrepisaneTerapiej().toString()+"\n");
end


rule "da li je sinusnaInfekcija"
agenda-group "prva"
salience 107
enabled false
	when
		$p: Pregled( $mog: moguceBolesti , $pro : najboljaProcenaBolesti  )
		$s : List(size >0) from collect( $m : MogucaBolest( mogucnost == $pro && naziv == sinusnaInfekcija.getNazivBolesti()) from $mog
		)
	then

		PrepisanaTerapija t = new PrepisanaTerapija(sinusnaInfekcija,null,null,null);
		$p.getPacient().getTerapije().add(t);
		
			int temp = $p.getPacient().getTerapije().size();
			System.out.println("\nbolest koja je izabrana je sinusnaInfekcija: \n"+$p.getPacient().getTerapije().
			get(temp-1).getBolest().toString()+"\n");
end


rule "reset"
salience -1000
	when
		$p : Pregled(  )
	then
		delete($p);
end
