package com.baske.model;

public enum SastojakLeka {
	VARFARIN_NATRIJUM, LAKTOZA_MONOHIDRAT, KUKURUZNI_SKROB, CELULOZA_MIKROKRISTAL, POVIDON, MAGNEZIJUM_STEARAT,
	ACETILSALICILNE_KISELINE, ALUMINIJUM_HIDROKSID, MAGNEZIJUM_HIDROKSID, POVIDON_K_30, KROSPOVIDON,
	CEFALEKSIN_MONOHIDRAT, ZELATIN, TITAN_DIOKSID_E171, BOJA_PATENT_BLUE_E131, BOJA_ERYTROSINE_E127

}
