package com.baske.model;

public enum Simptomi {
	CURENJE_IZ_NOSA, BOL_U_GRLU, GLAVOBOLJA, KIJANJE, KASALJ, TEMPERATURA_VECA_OD_38, DRHTAVICA,
	BOL_KOJI_SE_SIRI_OD_USIJU, TEMPERATURA_OD_40_DO_41, GUBITAK_APETITA, UMOR, ZUTI_SEKRET_IZ_NOSA,
	BOLOVANJE_OD_PREHLADE_ILI_GROZNICE_U_POSEDNJIH_60_DANA, OTICANJE_OKO_OCIJU,
	U_POSLEDNJIH_6_MESECI_ZABELEZNO_BAREM_10_SLUCAJEVA_UKOJEM_JE_PACIJENT_IMAO_VISOK_PRITISAK, CESTO_URINIRANJE,
	GUBITAK_TELESNE_TEZINE, ZAMOR, MUCNINA_I_POVRACANJE, NOCTURIA, OTOCI_NOGU_I_ZGLOBOVA, BOL_U_GRUDIMA, GUSENJE,
	DIJAREJA,
}
