package com.baske.model;

public enum SpecificanSimptom {
	PACIENT_BOLUJE_OD_HIPERTENZIJE_VISE_OD_6_MESECI,
	PACIENT_BOLUJE_OD_DIJABETESA,
	OPORAVLJA_SE_OD_OPERACIJE,
	U_POSLEDNJIH_14_DAN_POVISENA_TEMPERATURA,
	U_POSLEDNJIH_21_DAN_PREPISANI_ANTIBIOTICI
	

}
